size = {2048, 2048}

defineProperty("hot_start", globalPropertyf("sim/operation/prefs/startup_running"))


defineProperty("battery_on_1", globalPropertyi("sim/cockpit2/electrical/battery_on[0]"))
defineProperty("battery_on_2", globalPropertyi("sim/cockpit2/electrical/battery_on[1]"))
defineProperty("battery_on_3", globalPropertyi("sim/cockpit2/electrical/battery_on[2]"))
defineProperty("inverter_on_1", globalPropertyi("sim/cockpit2/electrical/inverter_on[0]"))
defineProperty("inverter_on_2", globalPropertyi("sim/cockpit2/electrical/inverter_on[1]"))
defineProperty("inverter_on_3", globalPropertyi("sim/an148/inverter_on_3"))
defineProperty("generator_on_1", globalPropertyi("sim/cockpit2/electrical/generator_on[0]"))
defineProperty("generator_on_2", globalPropertyi("sim/cockpit2/electrical/generator_on[1]"))
defineProperty("hydraulic_quantity", globalPropertyf("sim/cockpit/misc/hydraulic_quantity"))	
defineProperty("hydraulic_quantity2", globalPropertyf("sim/cockpit/misc/hydraulic_quantity2"))
defineProperty("fl_fuel_tank", globalPropertyi("sim/an148/fl_fuel_tank"))
defineProperty("sl_fuel_tank", globalPropertyi("sim/an148/sl_fuel_tank"))
defineProperty("fr_fuel_tank", globalPropertyi("sim/an148/fr_fuel_tank"))
defineProperty("sr_fuel_tank", globalPropertyi("sim/an148/sr_fuel_tank"))
defineProperty("fm_fuel_tank", globalPropertyi("sim/an148/fm_fuel_tank"))
defineProperty("sm_fuel_tank", globalPropertyi("sim/an148/sm_fuel_tank"))
defineProperty("eng1_inlet", globalPropertyi("sim/cockpit2/ice/ice_inlet_heat_on_per_engine[0]"))
defineProperty("eng2_inlet", globalPropertyi("sim/cockpit2/ice/ice_inlet_heat_on_per_engine[1]"))
defineProperty("wing_heat", globalPropertyi("sim/cockpit2/ice/ice_surfce_heat_on"))
defineProperty("rudder_heat", globalPropertyi("sim/an148/rudder_heat"))
defineProperty("emer_pitot", globalPropertyi("sim/an148/emer_pitot"))
defineProperty("pitot1", globalPropertyi("sim/cockpit2/ice/ice_pitot_heat_on_pilot"))
defineProperty("pitot2", globalPropertyi("sim/cockpit2/ice/ice_pitot_heat_on_copilot"))
defineProperty("APU_running", globalPropertyi("sim/cockpit/engine/APU_running"))
defineProperty("APU_switch", globalPropertyi("sim/cockpit/engine/APU_switch"))
defineProperty("APU_bleed", globalPropertyi("sim/cockpit/pressure/bleed_air_mode"))
defineProperty("APU_N1", globalPropertyf("sim/cockpit/engine/APU_N1"))


if get(hot_start) == 1 then
	set(battery_on_1, 1)
	set(battery_on_2, 1)
	set(battery_on_3, 1)
	set(inverter_on_1, 1)
	set(inverter_on_2, 1)
	set(inverter_on_3, 1)
	set(generator_on_1, 1)
	set(generator_on_2, 1)
	set(hydraulic_quantity, 1)	
	set(hydraulic_quantity2, 1)
	set(fl_fuel_tank, 1)
	set(sl_fuel_tank, 1)
	set(fr_fuel_tank, 1)
	set(sr_fuel_tank, 1)
	set(fm_fuel_tank, 1)
	set(sm_fuel_tank, 1)
	set(eng1_inlet, 1)
	set(eng2_inlet, 1)
	set(wing_heat, 1)
	set(rudder_heat, 1)
	set(emer_pitot, 1)
	set(pitot1, 1)
	set(pitot2, 1)
	set(APU_running, 0)
	set(APU_switch, 0)
	set(APU_bleed, 0)
	set(APU_N1, 0)
end
function update()
end